services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: controlfinanzas
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mypassword
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge